<?php
/* COUNTRIES */
class Country {
	// int;
	// 0: absent
	// 1: native
	// 2: extirpated
	// 3: introduced
	// 4: doubtful (explain in comments)
	public $presence;
	public $source;
	public $comment;
	function __construct($presence, $source, $comment = '') {
		$cpres = rencode($presence);
		if($cpres === false) {
			echo 'Invalid input to Country::__construct(): ' . $presence . PHP_EOL;
			return;
		}
		else $this->presence = $cpres;
		$this->source = $source;
		$this->comment = $comment;
	}
}
function rencode($in) {
	switch(strtolower($in)) {
		case '0': case 'absent': return 0;
		case '1': case 'present': case 'native': return 1;
		case '2': case 'extirpated': case 'extinct': case 'regionally extinct': return 2;
		case '3': case 'introduced': return 3;
		case '4': case 'doubtful': case 'presence uncertain': case 'possibly extinct': case 'reintroduced': case 'present - origin uncertain': case 'vagrant': return 4;
		default: return false;
	}
}
function rdecode($in) {
	switch($in) {
		case 0: return 'absent';
		case 1: return 'present';
		case 2: return 'extirpated';
		case 3: return 'introduced';
		case 4: return 'doubtful';
		default: return false;
	}
}
function cencode($in) {
// using ISO 3166-1-numeric codes with some additions
	switch($in) {
		case 'Afghanistan': return '004';
		case 'Akrotiri and Dhekelia': return '900';
		case 'Aland': case 'Aland Islands': case 'Åland': case 'Åland Islands': return '248';
		case 'Albania': return '008';
		case 'Algeria': return '012';
		case 'American Samoa': return '016';
		case 'Andorra': return '020';
		case 'Angola': return '024';
		case 'Anguilla': return '660';
		case 'Antarctica': return '010';
		case 'Antigua and Barbuda': return '028';
		case 'Argentina': return '032';
		case 'Armenia': return '051';
		case 'Aruba': return '533';
		case 'Ascension': return '901';
		case 'Ashmore and Cartier': case 'Ashmore and Cartier Islands': return '902';
		case 'Australia': return '036';
		case 'Austria': return '040';
		case 'Azerbaijan': return '031';
		case 'Bahamas': return '044';
		case 'Bahrain': return '048';
		case 'Baker': case 'Baker Island': return '903';
		case 'Bangladesh': return '050';
		case 'Barbados': return '052';
		case 'Belarus': return '112';
		case 'Belgium': return '056';
		case 'Belize': return '084';
		case 'Benin': return '204';
		case 'Bermuda': return '060';
		case 'Bhutan': return '064';
		case 'Bolivia': case 'Bolivia, Plurinational State of': return '068';
		case 'Bonaire': return '904';
		case 'BiH': case 'Bosnia and Herzegovina': return '070';
		case 'Botswana': return '072';
		case 'Bouvet': case 'Bouvet Island': return '074';
		case 'Brazil': return '076';
		case 'British Indian Ocean Territory': return '086';
		case 'Brunei': case 'Brunei Darussalam': return '096';
		case 'Bulgaria': return '100';
		case 'Burkina Faso': return '854';
		case 'Burundi': return '108';
		case 'Cambodia': return '116';
		case 'Cameroon': return '120';
		case 'Canada': return '124';
		case 'Cape Verde': return '132';
		case 'Cayman': case 'Cayman Islands': return '136';
		case 'CAR': case 'Central African Republic': return '140';
		case 'Chad': return '148';
		case 'Chile': return '152';
		case 'China': return '156';
		case 'Christmas': case 'Christmas Island': return '162';
		case 'Clipperton': case 'Clipperton Island': return '905';
		case 'Cocos': case 'Cocos Islands': case 'Cocos (Keeling)': case 'Cocos (Keeling) Islands': return '166';
		case 'Colombia': return '170';
		case 'Comoros': return '174';
		case 'Republic of Congo': case 'Congo': return '178';
		case 'DRC': case 'Democratic Republic of the Congo': case 'Congo, the Democratic Republic of the': case 'Congo, The Democratic Republic of the': return '180';
		case 'Cook': case 'Cook Islands': return '184';
		case 'Coral Sea': case 'Coral Sea Islands': return '906';
		case 'Costa Rica': return '188';
		case 'Côte d\'Ivoire': return '384';
		case 'Croatia': return '191';
		case 'Cuba': return '192';
		case 'Curaçao': return '531';
		case 'Cyprus': return '196';
		case 'Czech Republic': return '203';
		case 'Denmark': return '208';
		case 'Defunct country': case 'Netherlands Antilles': case 'Disputed Territory': case 'United States Minor Outlying Islands': return '920';
		case 'Djibouti': return '262';
		case 'Dominica': return '212';
		case 'Dominican Republic': return '214';
		case 'Ecuador': return '218';
		case 'Egypt': return '818';
		case 'El Salvador': return '222';
		case 'Equatorial Guinea': return '226';
		case 'Eritrea': return '232';
		case 'Estonia': return '233';
		case 'Ethiopia': return '231';
		case 'Falkland': case 'Falkland Islands': case 'Falkland Islands (Malvinas)': return '238';
		case 'Faroe': case 'Faroe Islands': return '234';
		case 'Fiji': return '242';
		case 'Finland': return '246';
		case 'France': return '250';
		case 'French Guiana': return '254';
		case 'French Polynesia': return '258';
		case 'French Southern Territories': case 'French Southern Territories (the)': return '260';
		case 'Gabon': return '266';
		case 'Gambia': return '270';
		case 'Georgia': return '268';
		case 'Germany': return '276';
		case 'Ghana': return '288';
		case 'Gibraltar': return '292';
		case 'Greece': return '300';
		case 'Greenland': return '304';
		case 'Grenada': return '308';
		case 'Guadeloupe': return '312';
		case 'Guam': return '316';
		case 'Guatemala': return '320';
		case 'Guernsey': return '831';
		case 'Guinea': return '324';
		case 'Guinea-Bissau': return '624';
		case 'Guyana': return '328';
		case 'Haiti': return '332';
		case 'Heard Island and McDonald': case 'Heard Island and McDonald Islands': return '334';
		case 'Vatican City': case 'Holy See (Vatican City State)': return '336';
		case 'Honduras': return '340';
		case 'Hong Kong': return '344';
		case 'Howland': case 'Howland Island': return '907';
		case 'Hungary': return '348';
		case 'Iceland': return '352';
		case 'India': return '356';
		case 'Indonesia': return '360';
		case 'Iran': case 'Iran, Islamic Republic of': return '364';
		case 'Iraq': return '368';
		case 'Ireland': return '372';
		case 'Isle of Man': return '833';
		case 'Israel': return '376';
		case 'Italy': return '380';
		case 'Jamaica': return '388';
		case 'Japan': return '392';
		case 'Jarvis': case 'Jarvis Island': return '907';
		case 'Jersey': return '832';
		case 'Johnston Atoll': return '908';
		case 'Jordan': return '400';
		case 'Kazakhstan': return '398';
		case 'Kenya': return '404';
		case 'Kingman Reef': return '909';
		case 'Kiribati': return '296';
		case 'North Korea': case 'Korea, Democratic People\'s Republic of': return '408';
		case 'South Korea': case 'Korea, Republic of': return '410';
		case 'Kosovo': return '910';
		case 'Kuwait': return '414';
		case 'Kyrgyzstan': return '417';
		case 'Laos': case 'Lao People\'s Democratic Republic': return '418';
		case 'Latvia': return '428';
		case 'Lebanon': return '422';
		case 'Lesotho': return '426';
		case 'Liberia': return '430';
		case 'Libya': case 'Libyan Arab Jamahiriya': return '434';
		case 'Liechtenstein': return '438';
		case 'Lithuania': return '440';
		case 'Luxembourg': return '442';
		case 'Macao': return '446';
		case 'Macedonia': case 'Macedonia, the former Yugoslav Republic of': return '807';
		case 'Madagascar': return '450';
		case 'Malawi': return '454';
		case 'Malaysia': return '458';
		case 'Maldives': return '462';
		case 'Mali': return '466';
		case 'Malta': return '470';
		case 'Marshall': case 'Marshall Islands': return '584';
		case 'Martinique': return '474';
		case 'Mauritania': return '478';
		case 'Mauritius': return '480';
		case 'Mayotte': return '175';
		case 'Mexico': return '484';
		case 'Micronesia': case 'Micronesia, Federated States of': return '583';
		case 'Midway Atoll': return '911';
		case 'Moldova': case 'Moldova, Republic of': return '498';
		case 'Monaco': return '492';
		case 'Mongolia': return '496';
		case 'Montenegro': return '499';
		case 'Montserrat': return '500';
		case 'Morocco': return '504';
		case 'Mozambique': return '508';
		case 'Myanmar': return '104';
		case 'Namibia': return '516';
		case 'Nauru': return '520';
		case 'Navassa': case 'Navassa Island': return '912';
		case 'Nepal': return '524';
		case 'Netherlands': return '528';
		case 'New Caledonia': return '540';
		case 'New Zealand': return '554';
		case 'Nicaragua': return '558';
		case 'Niger': return '562';
		case 'Nigeria': return '566';
		case 'Niue': return '570';
		case 'Norfolk': case 'Norfolk Island': return '574';
		case 'Northern Mariana': case 'Northern Marianas': case 'Northern Mariana Islands': return '580';
		case 'Norway': return '578';
		case 'Oman': return '512';
		case 'Pakistan': return '586';
		case 'Palau': return '585';
		case 'Palestine': case 'Palestinian territories': case 'Palestinian Territory, Occupied': return '275';
		case 'Palmyra': case 'Palmyra Atoll': return '913';
		case 'Panama': return '591';
		case 'PNG': case 'Papua New Guinea': return '598';
		case 'Paraguay': return '600';
		case 'Peru': return '604';
		case 'Philippines': return '608';
		case 'Pitcairn Islands': case 'Pitcairn': return '612';
		case 'Poland': return '616';
		case 'Portugal': return '620';
		case 'Puerto Rico': return '630';
		case 'Qatar': return '634';
		case 'Reunion': case 'Réunion': return '638';
		case 'Romania': return '642';
		case 'Russia': case 'Russian Federation': return '643';
		case 'Rwanda': return '646';
		case 'Saba': return '914';
		case 'Saint Barthelemy': case 'Saint Barthélemy': return '652';
		case 'Saint Eustatius': return '915';
		case 'Saint Helena': return '916';
		case 'Saint Kitts and Nevis': return '659';
		case 'Saint Lucia': return '662';
		case 'Saint Martin': case 'Saint Martin (French part)': return '663';
		case 'Saint Pierre and Miquelon': return '666';
		case 'Saint Vincent': case 'SVG': case 'Saint Vincent and the Grenadines': return '670';
		case 'Samoa': return '882';
		case 'San Marino': return '674';
		case 'São Tomé and Príncipe': case 'Sao Tome and Principe': case 'Sao Tomé and Principe': return '678';
		case 'Saudi Arabia': return '682';
		case 'Sea':
		case 'Arctic Sea':
		case 'Indian Ocean &amp;ndash; western':
		case 'Indian Ocean &amp;ndash; eastern':
		case 'Pacific &amp;ndash; northwest':
		case 'Pacific &amp;ndash; northeast':
		case 'Pacific &amp;ndash; southeast':
		case 'Pacific &amp;ndash; southwest':
		case 'Pacific &amp;ndash; western central':
		case 'Pacific &amp;ndash; eastern central':
		case 'Pacific &amp;ndash; Antarctic':
		case 'Atlantic &amp;ndash; western central':
		case 'Atlantic &amp;ndash; eastern central':
		case 'Atlantic &amp;ndash; northwest':
		case 'Atlantic &amp;ndash; northeast':
		case 'Atlantic &amp;ndash; southwest':
		case 'Atlantic &amp;ndash; southeast':
		case 'Atlantic &amp;ndash; Antarctic':
		case 'Indian Ocean &amp;ndash; Antarctic':
		case 'Mediterranean and Black Sea': return '919';
		case 'Senegal': return '686';
		case 'Serbia': return '688';
		case 'Seychelles': return '690';
		case 'Sierra Leone': return '694';
		case 'Singapore': return '702';
		case 'Sint Maarten': case 'Sint Maarten (Dutch part)': return '534';
		case 'Slovakia': return '703';
		case 'Slovenia': return '705';
		case 'Solomon': case 'Solomon Islands': return '090';
		case 'Somalia': return '706';
		case 'South Africa': return '710';
		case 'South Georgia': case 'South Georgia and the South Sandwich': case 'South Georgia and the South Sandwich Islands': return '239';
		case 'Spain': return '724';
		case 'Sri Lanka': return '144';
		case 'Sudan': return '736';
		case 'Suriname': return '740';
		case 'Svalbard': case 'Jan Mayen': case 'Svalbard and Jan Mayen': return '744';
		case 'Swaziland': return '748';
		case 'Sweden': return '752';
		case 'Switzerland': return '756';
		case 'Syria': case 'Syrian Arab Republic': return '760';
		case 'Taiwan': case 'ROC': case 'Republic of China': case 'Taiwan, Province of China': return '158';
		case 'Tajikistan': return '762';
		case 'Tanzania': case 'Tanzania, United Republic of': return '834';
		case 'Thailand': return '764';
		case 'East Timor': case 'Timor-Leste': return '626';
		case 'Togo': return '768';
		case 'Tokelau': return '772';
		case 'Tonga': return '776';
		case 'Trinidad': case 'Trinidad and Tobago': return '780';
		case 'Tristan da Cunha': return '917';
		case 'Tunisia': return '788';
		case 'Turkey': return '792';
		case 'Turkmenistan': return '795';
		case 'Turks and Caicos': case 'Turks and Caicos Islands': return '796';
		case 'Tuvalu': return '798';
		case 'Uganda': return '800';
		case 'Ukraine': return '804';
		case 'UAE': case 'United Arab Emirates': return '784';
		case 'UK': case 'United Kingdom': return '826';
		case 'US': case 'USA': case 'United States': return '840';
		case 'Uruguay': return '858';
		case 'Uzbekistan': return '860';
		case 'Vanuatu': return '548';
		case 'Venezuela': case 'Venezuela, Bolivarian Republic of': return '862';
		case 'Vietnam': case 'Viet Nam': return '704';
		case 'British Virgin': case 'BVI': case 'British Virgin Islands': case 'Virgin Islands, British': return '092';
		case 'USVI': case 'United States Virgin': case 'United States Virgin Islands': case 'Virgin Islands, U.S.': return '850';
		case 'Wake': case 'Wake Island': return '918';
		case 'Wallis and Futuna': return '876';
		case 'Western Sahara': return '732';
		case 'Yemen': return '887';
		case 'Zambia': return '894';
		case 'Zimbabwe': return '716';
		default: return false;
	}
}
function cdecode($in) {
// using ISO 3166-1-numeric codes with some additions
	switch($in) {
		case '004': return 'Afghanistan';
		case '008': return 'Albania';
		case '010': return 'Antarctica';
		case '012': return 'Algeria';
		case '016': return 'American Samoa';
		case '020': return 'Andorra';
		case '024': return 'Angola';
		case '028': return 'Antigua and Barbuda';
		case '031': return 'Azerbaijan';
		case '032': return 'Argentina';
		case '036': return 'Australia';
		case '040': return 'Austria';
		case '044': return 'Bahamas';
		case '048': return 'Bahrain';
		case '050': return 'Bangladesh';
		case '051': return 'Armenia';
		case '052': return 'Barbados';
		case '056': return 'Belgium';
		case '060': return 'Bermuda';
		case '064': return 'Bhutan';
		case '068': return 'Bolivia';
		case '070': return 'Bosnia and Herzegovina';
		case '072': return 'Botswana';
		case '074': return 'Bouvet';
		case '076': return 'Brazil';
		case '084': return 'Belize';
		case '086': return 'British Indian Ocean Territory';
		case '090': return 'Solomon Islands';
		case '092': return 'British Virgin Islands';
		case '096': return 'Brunei';
		case '100': return 'Bulgaria';
		case '104': return 'Myanmar';
		case '108': return 'Burundi';
		case '112': return 'Belarus';
		case '116': return 'Cambodia';
		case '120': return 'Cameroon';
		case '124': return 'Canada';
		case '132': return 'Cape Verde';
		case '136': return 'Cayman Islands';
		case '140': return 'Central African Republic';
		case '144': return 'Sri Lanka';
		case '148': return 'Chad';
		case '152': return 'Chile';
		case '156': return 'China';
		case '158': return 'Taiwan';
		case '162': return 'Christmas Island';
		case '166': return 'Cocos Islands';
		case '170': return 'Colombia';
		case '174': return 'Comoros';
		case '175': return 'Mayotte';
		case '178': return 'Republic of Congo';
		case '180': return 'Democratic Republic of the Congo';
		case '184': return 'Cook Islands';
		case '188': return 'Costa Rica';
		case '191': return 'Croatia';
		case '192': return 'Cuba';
		case '196': return 'Cyprus';
		case '203': return 'Czech Republic';
		case '204': return 'Benin';
		case '208': return 'Denmark';
		case '212': return 'Dominica';
		case '214': return 'Dominican Republic';
		case '218': return 'Ecuador';
		case '222': return 'El Salvador';
		case '226': return 'Equatorial Guinea';
		case '231': return 'Ethiopia';
		case '232': return 'Eritrea';
		case '233': return 'Estonia';
		case '234': return 'Faroe Islands';
		case '238': return 'Falkland Islands';
		case '239': return 'South Georgia and the South Sandwich Islands';
		case '242': return 'Fiji';
		case '246': return 'Finland';
		case '248': return 'Åland';
		case '250': return 'France';
		case '254': return 'French Guiana';
		case '258': return 'French Polynesia';
		case '260': return 'French Southern Territories';
		case '262': return 'Djibouti';
		case '266': return 'Gabon';
		case '268': return 'Georgia';
		case '270': return 'Gambia';
		case '275': return 'Palestine';
		case '276': return 'Germany';
		case '288': return 'Ghana';
		case '292': return 'Gibraltar';
		case '296': return 'Kiribati';
		case '300': return 'Greece';
		case '304': return 'Greenland';
		case '308': return 'Grenada';
		case '312': return 'Guadeloupe';
		case '316': return 'Guam';
		case '320': return 'Guatemala';
		case '324': return 'Guinea';
		case '328': return 'Guyana';
		case '332': return 'Haiti';
		case '334': return 'Heard Island and McDonald Islands';
		case '336': return 'Vatican City';
		case '340': return 'Honduras';
		case '344': return 'Hong Kong';
		case '348': return 'Hungary';
		case '352': return 'Iceland';
		case '356': return 'India';
		case '360': return 'Indonesia';
		case '364': return 'Iran';
		case '368': return 'Iraq';
		case '372': return 'Ireland';
		case '376': return 'Israel';
		case '380': return 'Italy';
		case '384': return 'Côte d\'Ivoire';
		case '388': return 'Jamaica';
		case '392': return 'Japan';
		case '398': return 'Kazakhstan';
		case '400': return 'Jordan';
		case '404': return 'Kenya';
		case '408': return 'North Korea';
		case '410': return 'South Korea';
		case '414': return 'Kuwait';
		case '417': return 'Kyrgyzstan';
		case '418': return 'Laos';
		case '422': return 'Lebanon';
		case '426': return 'Lesotho';
		case '428': return 'Latvia';
		case '430': return 'Liberia';
		case '434': return 'Libya';
		case '438': return 'Liechtenstein';
		case '440': return 'Lithuania';
		case '442': return 'Luxembourg';
		case '446': return 'Macao';
		case '450': return 'Madagascar';
		case '454': return 'Malawi';
		case '458': return 'Malaysia';
		case '462': return 'Maldives';
		case '466': return 'Mali';
		case '470': return 'Malta';
		case '474': return 'Martinique';
		case '478': return 'Mauritania';
		case '480': return 'Mauritius';
		case '484': return 'Mexico';
		case '492': return 'Monaco';
		case '496': return 'Mongolia';
		case '498': return 'Moldova';
		case '499': return 'Montenegro';
		case '500': return 'Montserrat';
		case '504': return 'Morocco';
		case '508': return 'Mozambique';
		case '512': return 'Oman';
		case '516': return 'Namibia';
		case '520': return 'Nauru';
		case '524': return 'Nepal';
		case '528': return 'Netherlands';
		case '531': return 'Curaçao';
		case '533': return 'Aruba';
		case '534': return 'Sint Maarten (Dutch part)';
		case '540': return 'New Caledonia';
		case '548': return 'Vanuatu';
		case '554': return 'New Zealand';
		case '558': return 'Nicaragua';
		case '562': return 'Niger';
		case '566': return 'Nigeria';
		case '570': return 'Niue';
		case '574': return 'Norfolk';
		case '578': return 'Norway';
		case '580': return 'Northern Marianas';
		case '583': return 'Micronesia';
		case '584': return 'Marshall Islands';
		case '585': return 'Palau';
		case '586': return 'Pakistan';
		case '591': return 'Panama';
		case '598': return 'Papua New Guinea';
		case '600': return 'Paraguay';
		case '604': return 'Peru';
		case '608': return 'Philippines';
		case '612': return 'Pitcairn Islands';
		case '616': return 'Poland';
		case '620': return 'Portugal';
		case '624': return 'Guinea-Bissau';
		case '626': return 'East Timor';
		case '630': return 'Puerto Rico';
		case '634': return 'Qatar';
		case '638': return 'Réunion';
		case '642': return 'Romania';
		case '643': return 'Russia';
		case '646': return 'Rwanda';
		case '652': return 'Saint Barthélemy';
		case '659': return 'Saint Kitts and Nevis';
		case '660': return 'Anguilla';
		case '662': return 'Saint Lucia';
		case '663': return 'Saint Martin (French part)';
		case '666': return 'Saint Pierre and Miquelon';
		case '670': return 'Saint Vincent and the Grenadines';
		case '674': return 'San Marino';
		case '678': return 'São Tomé and Príncipe';
		case '682': return 'Saudi Arabia';
		case '686': return 'Senegal';
		case '688': return 'Serbia';
		case '690': return 'Seychelles';
		case '694': return 'Sierra Leone';
		case '702': return 'Singapore';
		case '703': return 'Slovakia';
		case '704': return 'Vietnam';
		case '705': return 'Slovenia';
		case '706': return 'Somalia';
		case '710': return 'South Africa';
		case '716': return 'Zimbabwe';
		case '724': return 'Spain';
		case '732': return 'Western Sahara';
		case '736': return 'Sudan';
		case '740': return 'Suriname';
		case '744': return 'Svalbard and Jan Mayen';
		case '748': return 'Swaziland';
		case '752': return 'Sweden';
		case '756': return 'Switzerland';
		case '760': return 'Syria';
		case '762': return 'Tajikistan';
		case '764': return 'Thailand';
		case '768': return 'Togo';
		case '772': return 'Tokelau';
		case '776': return 'Tonga';
		case '780': return 'Trinidad';
		case '784': return 'United Arab Emirates';
		case '788': return 'Tunisia';
		case '792': return 'Turkey';
		case '795': return 'Turkmenistan';
		case '796': return 'Turks and Caicos Islands';
		case '798': return 'Tuvalu';
		case '800': return 'Uganda';
		case '804': return 'Ukraine';
		case '807': return 'Macedonia';
		case '818': return 'Egypt';
		case '826': return 'United Kingdom';
		case '831': return 'Guernsey';
		case '832': return 'Jersey';
		case '833': return 'Isle of Man';
		case '834': return 'Tanzania';
		case '840': return 'United States';
		case '850': return 'United States Virgin Islands';
		case '854': return 'Burkina Faso';
		case '858': return 'Uruguay';
		case '860': return 'Uzbekistan';
		case '862': return 'Venezuela';
		case '876': return 'Wallis and Futuna';
		case '882': return 'Samoa';
		case '887': return 'Yemen';
		case '894': return 'Zambia';
		case '900': return 'Akrotiri and Dhekelia';
		case '901': return 'Ascension';
		case '902': return 'Ashmore and Cartier Islands';
		case '903': return 'Baker Island';
		case '904': return 'Bonaire';
		case '905': return 'Clipperton';
		case '906': return 'Coral Sea Islands';
		case '907': return 'Howland Island';
		case '907': return 'Jarvis Island';
		case '908': return 'Johnston Atoll';
		case '909': return 'Kingman Reef';
		case '910': return 'Kosovo';
		case '911': return 'Midway Atoll';
		case '912': return 'Navassa Island';
		case '913': return 'Palmyra Atoll';
		case '914': return 'Saba';
		case '915': return 'Saint Eustatius';
		case '916': return 'Saint Helena';
		case '917': return 'Tristan da Cunha';
		case '918': return 'Wake Island';
		case '919': return 'Sea';
		case '920': return 'Defunct country';
		default: return false;
	}
}
